store/Controllers/ShopController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using store.Models;
using static store.Models.ViewModel;
using store.Common;
using System.Data;
using System.Data.SqlClient;
using Dapper;
using System.IO;
using System.Collections.Generic;
using System.Net.Mail;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.html.simpleparser;

namespace store.Controllers
{
    public class ShopController : Controller
    {




        static string loc1 = "";

        static object lockObj = new object();//for remains value static ...
        MallManagementEntities db = new MallManagementEntities();

        #region Registration help files
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ShopController()
        {
        }

        public ShopController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

        #region Helpers
        // Used for XSRF protection when adding external logins
        private const string XsrfKey = "XsrfId";
        private string MallOwnerID;

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public object PageSize { get; private set; }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        internal class ChallengeResult : HttpUnauthorizedResult
        {
            public ChallengeResult(string provider, string redirectUri)
                : this(provider, redirectUri, null)
            {
            }

            public ChallengeResult(string provider, string redirectUri, string userId)
            {
                LoginProvider = provider;
                RedirectUri = redirectUri;
                UserId = userId;
            }

            public string LoginProvider { get; set; }
            public string RedirectUri { get; set; }
            public string UserId { get; set; }

            public override void ExecuteResult(ControllerContext context)
            {
                var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
                if (UserId != null)
                {
                    properties.Dictionary[XsrfKey] = UserId;
                }
                context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
            }
        }
        #endregion

        #region  Shop Owner registration
        public ActionResult ShopOwnerDetails()
        {
            //ViewBag.abc = "Registered Succesffully";
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> ShopOwnerDetails(ShopOwnerViewModel DetailsPost, HttpPostedFileBase MyImage)
        {

            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = DetailsPost.EmailID, Email = DetailsPost.EmailID };
                var result = await UserManager.CreateAsync(user, DetailsPost.Password);
                if (result.Succeeded)
                {
                    UserManager.AddToRole(user.Id, "ShopOwner");


                    ShopOwnerDetailsTbl NewAdd = new ShopOwnerDetailsTbl();
                    NewAdd.ShopOwnerID = user.Id;
                    NewAdd.Name = DetailsPost.Name;
                    NewAdd.Address = DetailsPost.Address;
                    NewAdd.EmailID = DetailsPost.EmailID;
                    if (DetailsPost.DOB != null && DetailsPost.DOB != "")
                    {
                        var Date = DateTime.ParseExact(DetailsPost.DOB, "dd-MM-yyyy", CultureInfo.InvariantCulture);
                        NewAdd.DOB = Date;
                    }
                    NewAdd.Age = DetailsPost.Age;
                    NewAdd.PhnNo = DetailsPost.PhnNo;
                    NewAdd.Gender = DetailsPost.Gender;
                    db.ShopOwnerDetailsTbls.Add(NewAdd);
                    db.SaveChanges();
                    //for image upload
                    if (MyImage != null && MyImage.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(MyImage.FileName);

                        fileName = NewAdd.ShopOwnerID + "-ShopOwner-Image-" + fileName;

                        var path = Path.Combine(Server.MapPath("~/Uploads/ShopOwner"), fileName);

                        MyImage.SaveAs(path); //image store in server

                        NewAdd.img = fileName; //imgage path,db
                    }
                    db.SaveChanges();
                    //TempData["Message"] = "Registered Successfully!";
                    // ViewBag.abc = NewAdd.MallOwnerID;
                    return RedirectToAction("Login", "Account");
                }
                AddErrors(result);
            }

            return View(DetailsPost);
            // return View();

        }
        #endregion

        #region Edit Actions.....

        //For shop Edit

        public ActionResult ShopEdit(int ShopID)
        {
            //ViewBag.abc = "Registered Succesffully";
            ViewBag.ShopCategoriesvar = db.ShopCategoryTbls.ToList();
            var ShopOwnerID = User.Identity.GetUserId();
            var Shop = db.ShopTbls.Where(x => x.ShopOwnerID == ShopOwnerID && x.ShopID == ShopID).FirstOrDefault();
            ShopOwnerShopViewModel EditModel = new ShopOwnerShopViewModel();
            EditModel.ShopName = Shop.ShopName;
            EditModel.PhnNo = Shop.PhnNo;
            EditModel.LicenceNo = Shop.LicenceNo;
            EditModel.ShopCategoryID = Shop.ShopCategoryID;
            EditModel.ShopID = Shop.ShopID;
            EditModel.img = Shop.img;
            return View(EditModel);

        }

        [HttpPost]
        public ActionResult ShopEdit(ShopOwnerShopViewModel DetailsPost, HttpPostedFileBase MyImage)
        {

            if (ModelState.IsValid)
            {
                //ViewBag.abc = "Registered Succesffully";
                var GetShop = db.ShopTbls.Where(x => x.ShopID == DetailsPost.ShopID).FirstOrDefault();

                GetShop.ShopName = DetailsPost.ShopName;
                GetShop.PhnNo = DetailsPost.PhnNo;
                GetShop.LicenceNo = DetailsPost.LicenceNo;
                GetShop.ShopCategoryID = DetailsPost.ShopCategoryID;
                db.SaveChanges();
                if (MyImage != null && MyImage.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(MyImage.FileName);

                    fileName = DetailsPost.ShopID + "-ShopOwner-Image-" + fileName;

                    var path = Path.Combine(Server.MapPath("~/Uploads/ShopOwner"), fileName);

                    MyImage.SaveAs(path); //image store in server

                    GetShop.img = fileName; //imgage path,db
                }
                db.SaveChanges();
                return RedirectToAction("ShopView");
            }

            ViewBag.ShopCategoriesvar = db.ShopCategoryTbls.ToList();
            return View(DetailsPost);
            // return View();

        }

        //for shop owner profile edit.......
        [Authorize(Roles = "ShopOwner")]
        public ActionResult ShopOwnerProfileEdit()
        {
            string ShopOwnerID = User.Identity.GetUserId();


            var CheckDetails = db.ShopOwnerDetailsTbls.Where(x => x.ShopOwnerID == ShopOwnerID).FirstOrDefault();
            if (CheckDetails != null)
            {

                ShopOwnerViewModel EditShopOwner = new ShopOwnerViewModel();

                EditShopOwner.Name = CheckDetails.Name;
                EditShopOwner.Address = CheckDetails.Address;
                EditShopOwner.EmailID = CheckDetails.EmailID;
                EditShopOwner.DOB = Convert.ToDateTime(CheckDetails.DOB).ToString("dd-MM-yyyy");
                EditShopOwner.Age = CheckDetails.Age;
                EditShopOwner.Gender = CheckDetails.Gender;
                EditShopOwner.PhnNo = CheckDetails.PhnNo;
                EditShopOwner.img = CheckDetails.img;


                return View(EditShopOwner);
            }

            return View("ViewProfile");
        }

        [HttpPost]
        public ActionResult ShopOwnerProfileEdit(ShopOwnerViewModel PostModel, HttpPostedFileBase MyImage)
        {

            string ShopOwnerID = User.Identity.GetUserId();

            var ShopOwnerUpdate = db.ShopOwnerDetailsTbls.Where(x => x.ShopOwnerID == ShopOwnerID).FirstOrDefault();

            if (ShopOwnerUpdate != null)
            {

store/Views/Shop/MallMsgInbox.cshtml
@*@model store.Models.ViewModel.ComplaintBoxViewModel*@
@using Microsoft.AspNet.Identity;
@model List<store.Models.ShopMallComplaintTbl>
@{
    ViewBag.Title = "ComplaintBox";
}

<h2>ComplaintBox</h2>
@Styles.Render("~/Contents/store.css")

@*@using (Html.BeginForm("MallMsgInbox", "Shop", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/holder/2.4.1/holder.js"></script>
    <div style="padding: 10px 10% 0 10%; background-color: #ffffff;">
    @foreach (var item in Model)
    {
        if(item.WhoStatus==true)
        {
        <div class="chat_list">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="pull-left hidden-xs">
                        <div>
                            <img class="img-circle" title="User1" alt="User1" data-src="holder.js/40x40/lava">
                        </div>
                    </div>
                    <small class="pull-right text-muted">@item.DatePosted</small>

                    <div>
                        <small class="list-group-item-heading text-muted text-primary">
                            @{
                                var db = new store.Models.MallManagementEntities();
                                var MOwner = db.MallOwnerDetailsTbls.ToList();
                                foreach (var id in MOwner)
                                {
                                    if (ViewBag.MallOWnerID == id.MallOwnerID)
                                    {
                                        @Html.DisplayFor(modelItem => id.OwnerName)
                                    }
                                }
                            }
                    }
                        </small>
                        <p class="list-group-item-text">
                            @Html.DisplayFor(modelItem=>item.Msg)
                        </p>

                    </div>
                </li>
            </ul>
        </div>
    </div>
    }*@


<div class="container">
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
    <div class="mail-box">
        <aside class="sm-side">
            <div class="user-head">
                <a class="inbox-avatar" href="javascript:;">
                    <img width="64" hieght="60" src="http://bootsnipp.com/img/avatars/ebeb306fd7ec11ab68cbcaa34282158bd80361a7.jpg">
                </a>
                <div class="user-name">
                    <h5><a href="#">Alireza Zare</a></h5>
                    <span><a href="#">Info.Ali.Pci@Gmail.com</a></span>
                </div>
                <a class="mail-dropdown pull-right" href="javascript:;">
                    <i class="fa fa-chevron-down"></i>
                </a>
            </div>
            <div class="inbox-body">
                <a href="#myModal" data-toggle="modal" title="Compose" class="btn btn-compose">
                    Compose
                </a>
                <!-- Modal -->
                <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade" style="display: none;">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                                <h4 class="modal-title">Compose</h4>
                            </div>
                            <div class="modal-body">
                                <form role="form" class="form-horizontal">
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label">To</label>
                                        <div class="col-lg-10">
                                            <input type="text" placeholder="" id="inputEmail1" class="form-control">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label">Cc / Bcc</label>
                                        <div class="col-lg-10">
                                            <input type="text" placeholder="" id="cc" class="form-control">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label">Subject</label>
                                        <div class="col-lg-10">
                                            <input type="text" placeholder="" id="inputPassword1" class="form-control">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label">Message</label>
                                        <div class="col-lg-10">
                                            <textarea rows="10" cols="30" class="form-control" id="" name=""></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="btn green fileinput-button">
                                                <i class="fa fa-plus fa fa-white"></i>
                                                <span>Attachment</span>
                                                <input type="file" name="files[]" multiple="">
                                            </span>
                                            <button class="btn btn-send" type="submit">Send</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
            </div>
            <ul class="inbox-nav inbox-divider">
                <li class="active">
                    <a href="#"><i class="fa fa-inbox"></i> Inbox <span class="label label-danger pull-right">2</span></a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-envelope-o"></i> Sent Mail</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-bookmark-o"></i> Important</a>
                </li>
                <li>
                    <a href="#"><i class=" fa fa-external-link"></i> Drafts <span class="label label-info pull-right">30</span></a>
                </li>
                <li>
                    <a href="#"><i class=" fa fa-trash-o"></i> Trash</a>
                </li>
            </ul>
            <ul class="nav nav-pills nav-stacked labels-info inbox-divider">
                <li> <h4>Labels</h4> </li>
                <li> <a href="#"> <i class="fa fa-sign-blank text-danger"></i> Work </a> </li>
                <li> <a href="#"> <i class="fa fa-sign-blank text-success"></i> Design </a> </li>
                <li>
                    <a href="#"> <i class="fa fa-sign-blank text-info "></i> Family </a>
                </li>
                <li>
                    <a href="#"> <i class="fa fa-sign-blank text-warning "></i> Friends </a>
                </li>
                <li>
                    <a href="#"> <i class="fa fa-sign-blank text-primary "></i> Office </a>
                </li>
            </ul>
            <ul class="nav nav-pills nav-stacked labels-info ">
                <li> <h4>Buddy online</h4> </li>
                <li> <a href="#"> <i class="fa fa-circle text-success"></i>Alireza Zare <p>I do not think</p></a>  </li>
                <li> <a href="#"> <i class="fa fa-circle text-danger"></i>Dark Coders<p>Busy with coding</p></a> </li>
                <li>
                    <a href="#"> <i class="fa fa-circle text-muted "></i>Mentaalist <p>I out of control</p></a>
                </li>
                <li>
                    <a href="#"> <i class="fa fa-circle text-muted "></i>H3s4m<p>I am not here</p></a>
                </li>
                <li>
                    <a href="#"> <i class="fa fa-circle text-muted "></i>Dead man<p>I do not think</p></a>
                </li>
            </ul>
            <div class="inbox-body text-center">
                <div class="btn-group">
                    <a class="btn mini btn-primary" href="javascript:;">
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
                <div class="btn-group">
                    <a class="btn mini btn-success" href="javascript:;">
                        <i class="fa fa-phone"></i>
                    </a>
                </div>
                <div class="btn-group">
                    <a class="btn mini btn-info" href="javascript:;">
                        <i class="fa fa-cog"></i>
                    </a>
                </div>
            </div>
        </aside>
        <aside class="lg-side">
            <div class="inbox-head">
                <h3>Inbox</h3>
                <form action="#" class="pull-right position">
                    <div class="input-append">
                        <input type="text" class="sr-input" placeholder="Search Mail">
                        <button class="btn sr-btn" type="button"><i class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>
            <div class="inbox-body">
                <div class="mail-option">
                    <div class="chk-all">
                        <input type="checkbox" class="mail-checkbox mail-group-checkbox">
                        <div class="btn-group">
                            <a data-toggle="dropdown" href="#" class="btn mini all" aria-expanded="false">
                                All
                                <i class="fa fa-angle-down "></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#"> None</a></li>
                                <li><a href="#"> Read</a></li>
                                <li><a href="#"> Unread</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="btn-group">
                        <a data-original-title="Refresh" data-placement="top" data-toggle="dropdown" href="#" class="btn mini tooltips">
                            <i class="fa fa-refresh"></i>
                        </a>
                    </div>
                    <div class="btn-group hidden-phone">
                        <a data-toggle="dropdown" href="#" class="btn mini blue" aria-expanded="false">
                            More
                            <i class="fa fa-angle-down "></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-pencil"></i> Mark as Read</a></li>
                            <li><a href="#"><i class="fa fa-ban"></i> Spam</a></li>
                            <li class="divider"></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                        </ul>
                    </div>
                    <div class="btn-group">
                        <a data-toggle="dropdown" href="#" class="btn mini blue">
                            Move to
                            <i class="fa fa-angle-down "></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-pencil"></i> Mark as Read</a></li>
                            <li><a href="#"><i class="fa fa-ban"></i> Spam</a></li>
                            <li class="divider"></li>
                            <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
                        </ul>
                    </div>
                    <ul class="unstyled inbox-pagination">
                        <li><span>1-50 of 234</span></li>
                        <li>
                            <a class="np-btn" href="#"><i class="fa fa-angle-left  pagination-left"></i></a>
                        </li>
                        <li>
                            <a class="np-btn" href="#"><i class="fa fa-angle-right pagination-right"></i></a>
                        </li>
                    </ul>
                </div>
                <table class="table table-inbox table-hover">
                    <tbody>

                        <tr class="unread">
                            @foreach (var item in Model)
                            {
                                <td class="inbox-small-cells">
                                    <input type="checkbox" class="mail-checkbox">
                                </td>

                                <td class="view-message  dont-show">PHPClass</td>
                                <td class="view-message ">Added a new class: Login Class Fast Site</td>
                                <td class="view-message  inbox-small-cells"><i class="fa fa-paperclip"></i></td>
                                <td class="view-message  text-right">9:27 AM</td>
                            }
                        </tr>

                    </tbody>
                </table>
            </div>
        </aside>
    </div>
</div>                       

store/Views/Shop/MallRoomListEdit.cshtml
@model store.Models.ViewModel.ShopViewModel

@{
    ViewBag.Title = "MallRoomListEdit";
}
<hr>
<hr>
<body style="background-color:white">
    <h2>Edit your rooms here</h2>

    @using (Html.BeginForm("MallRoomListEdit", "Shop", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">


            @Html.HiddenFor(model => model.ShopID)

            <div class="form-group">
                @Html.LabelFor(model => model.RoomNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.RoomNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RoomNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FloorNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.FloorNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FloorNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SQFT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.SQFT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SQFT, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Amt, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Amt, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Amt, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <input type="button" value="Cancel" class="btn btn-primary"
                           onclick="location.href='@Request.UrlReferrer'" />
                </div>
            </div>
        </div>
    }
    </body>

store/Views/Shop/MallShopUserListView.cshtml
@model IEnumerable<store.Models.ShopOwnerDetailsTbl>
@{
    ViewBag.Title = "MallShopUserListView";
}
<br>
<body style="background-color:white">
    <h2>Shop Users</h2>
    @Styles.Render("~/Content/store.css")
   
        @{if (TempData["Message"] != null)
            {
                <script type="text/javascript">
                    window.onload = function () {
                        alert('@TempData["Message"]');
                    };
                </script>
            }
            var MallID = Request.QueryString["MallID"];
        }


        <h2 style="color:white;">List of Registered Owners</h2>
        @using (Html.BeginForm("MallShopUserListView", "Shop", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {

            @Html.AntiForgeryToken()
            <div class="row">
                <input type="submit" class="btn btn-primary" name="command" style="float: left;margin-right:10px;" value="AllUsers" />
                <input type="submit" class="btn btn-primary" name="command" style="float: left;margin-right:40px;" value="ShopRegisterdUsers" />


                @if (MallID != null)
                {
                    <a href="~/Shop/RegUsersReport?MallID@(MallID)" class="btn btn-primary">Get Report</a>
                }



                <input type="button" align="right" class="btn btn-primary" style="float: right;" value="Back" onclick="@("window.location.href='" + @Url.Action("MallOwnerShop", "Shop") + "'");" />
            </div>
            <hr>
        }
        @{
            if (!IsPost)
            {

                Html.RenderPartial("MallShopUserListViewPartial", Model);
            }
            else if (IsPost)
            {
                if (Request["command"].Equals("AllUsers"))
                {
                    Html.RenderPartial("MallShopUserListViewPartial", Model);
                }
                else
                {
                    var db = new store.Models.MallManagementEntities();

                    var ShopOwnerList = db.ShopOwnerDetailsTbls.ToList();

                    var OwnersWithList = new List<store.Models.ShopOwnerDetailsTbl>();

                    foreach (var Owner in ShopOwnerList)
                    {
                        var CheckMall = db.ShopTbls.Where(x => x.ShopOwnerID == Owner.ShopOwnerID).ToList();
                        if (CheckMall.Count() > 0)
                        {
                            OwnersWithList.Add(Owner);
                        }
                    }
                    Html.RenderPartial("MallShopUserListViewPartial", OwnersWithList);
                }
            }
        }
    </body>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

store/Views/Shop/SendShopMallMsg.cshtml
@model store.Models.ViewModel.ComplaintBoxViewModel
@{
    ViewBag.Title = "SendShopMallMsg";
}

@Html.AntiForgeryToken()
 @using (Html.BeginForm("SendShopMallMsg2", "Shop", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
 {
<div >

    <hr />

    <div class="form-group">
             
        <div class="col-md-10">
            @Html.DropDownListFor(x => x.ShopID, new SelectList(ViewBag.ShopVar, "ShopID", "ShopName"), "-- Select Shop --", new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
      
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Msg, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Msg, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Send" class="btn btn-primary" />
            <input type="button" value="Cancel" class="btn btn-primary"
                   onclick="location.href='@Request.UrlReferrer'" />
        </div>
    </div>
</div>

 }